export const USER_PENDING = 'USER_PENDING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';

export const MAIN_FEED_PENDING = 'MAIN_FEED_PENDING';
export const MAIN_FEED_PART = 'MAIN_FEED_PART';
export const MAIN_FEED_REFRESH = 'MAIN_FEED_REFRESH';
export const NEW_POST_CHANGE = 'NEW_POST_CHANGE';
export const NEW_POST_SAVE = 'NEW_POST_SAVE';
export const MAIN_FEED_ERROR = 'MAIN_FEED_ERROR';

export const USER_FEED_PENDING = 'USER_FEED_PENDING';
export const USER_FEED_PART = 'USER_FEED_PART';
export const USER_FEED_REFRESH = 'USER_FEED_REFRESH';
export const USER_FEED_ERROR = 'USER_FEED_ERROR';
